line-length = 120
target-version = "py312"

[lint]
select = [
  "F",      # Pyflakes
  "E",      # pycodestyle errors
  "W",      # pycodestyle warnings
  "I",      # isort
  "N",      # pep8-naming
  "UP",     # pyupgrade
  "B",      # flake8-bugbear (catches common bugs)
  "C4",     # flake8-comprehensions
  "PIE",    # flake8-pie
  "SIM",    # flake8-simplify
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Allow unused imports in __init__.py